### ISSUE TITLE
Fails for odd length input values

### ISSUE THREAD

**Issue by lenidh** [calmh/luhn#1]
Generates wrong check digits for odd length input values. This is caused by not altering the initial factor for different input lengths (must be done if processing the input from left to right).

Example from [Rosetta Code](http://rosettacode.org/wiki/Luhn_test_of_credit_card_numbers): For alphabet "0123456789" and input "123456781234567" expected check digit is "0" (actual generated check digit is "1").

**Comment by calmh** [comment]
Sounds like a bug, indeed.
